source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ViewDesign_Example', :exclusive => true do
    pod "ViewDesign", :path => "../"
end

target 'ViewDesign_Tests', :exclusive => true do
    pod "ViewDesign", :path => "../"
    
    
end
